Update contig.py
    # modified to rectify the AttributeError: 'list' object has no attribute 'search' error
    # seems to be caused by a single telomere rather than a list of multiple